import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import type { OmadaClient } from '../omadaClient/index.js';
import { registerDisableClientRateLimitTool } from './disableClientRateLimit.js';
import { registerGetAccessControlTool } from './getAccessControl.js';
import { registerGetAclConfigTypeSettingTool } from './getAclConfigTypeSetting.js';
import { registerGetAlgTool } from './getAlg.js';
import { registerGetAllDeviceBySiteTool } from './getAllDeviceBySite.js';
import { registerGetApDetailTool } from './getApDetail.js';
import { registerGetApGeneralConfigTool } from './getApGeneralConfig.js';
import { registerGetApLldpConfigTool } from './getApLldpConfig.js';
import { registerGetApplicationControlStatusTool } from './getApplicationControlStatus.js';
import { registerGetApRadiosTool } from './getApRadios.js';
import { registerGetApSnmpConfigTool } from './getApSnmpConfig.js';
import { registerGetApUplinkConfigTool } from './getApUplinkConfig.js';
import { registerGetApVlanConfigTool } from './getApVlanConfig.js';
import { registerGetAttackDefenseSettingTool } from './getAttackDefenseSetting.js';
import { registerGetBandSteeringSettingTool } from './getBandSteeringSetting.js';
import { registerGetBandwidthControlTool } from './getBandwidthControl.js';
import { registerGetBeaconControlSettingTool } from './getBeaconControlSetting.js';
import { registerGetCableTestFullResultsTool } from './getCableTestFullResults.js';
import { registerGetCableTestLogsTool } from './getCableTestLogs.js';
import { registerGetChannelLimitSettingTool } from './getChannelLimitSetting.js';
import { registerGetChannelsTool } from './getChannels.js';
import { registerGetClientTool } from './getClient.js';
import { registerGetClientDetailTool } from './getClientDetail.js';
import { registerGetClientsDistributionTool } from './getClientsDistribution.js';
import { registerGetDashboardMostActiveEapsTool } from './getDashboardMostActiveEaps.js';
import { registerGetDashboardMostActiveSwitchesTool } from './getDashboardMostActiveSwitches.js';
import { registerGetDashboardOverviewTool } from './getDashboardOverview.js';
import { registerGetDashboardPoEUsageTool } from './getDashboardPoEUsage.js';
import { registerGetDashboardSwitchSummaryTool } from './getDashboardSwitchSummary.js';
import { registerGetDashboardTopCpuUsageTool } from './getDashboardTopCpuUsage.js';
import { registerGetDashboardTopMemoryUsageTool } from './getDashboardTopMemoryUsage.js';
import { registerGetDashboardTrafficActivitiesTool } from './getDashboardTrafficActivities.js';
import { registerGetDashboardWifiSummaryTool } from './getDashboardWifiSummary.js';
import { registerGetDdnsGridTool } from './getDdnsGrid.js';
import { registerGetDeviceTool } from './getDevice.js';
import { registerGetDhcpReservationGridTool } from './getDhcpReservationGrid.js';
import { registerGetDnsCacheSettingTool } from './getDnsCacheSetting.js';
import { registerGetDnsProxyTool } from './getDnsProxy.js';
import { registerGetDownlinkWiredDevicesTool } from './getDownlinkWiredDevices.js';
import { registerGetEapDot1xSettingTool } from './getEapDot1xSetting.js';
import { registerGetFirewallSettingTool } from './getFirewallSetting.js';
import { registerGetFirmwareInfoTool } from './getFirmwareInfo.js';
import { registerGetGatewayDetailTool } from './getGatewayDetail.js';
import { registerGetGatewayLanStatusTool } from './getGatewayLanStatus.js';
import { registerGetGatewayPortsTool } from './getGatewayPorts.js';
import { registerGetGatewayWanStatusTool } from './getGatewayWanStatus.js';
import { registerGetGridAllowListTool } from './getGridAllowList.js';
import { registerGetGridAllowMacFilteringTool } from './getGridAllowMacFiltering.js';
import { registerGetGridAutoCheckUpgradeTool } from './getGridAutoCheckUpgrade.js';
import { registerGetGridBandwidthCtrlRuleTool } from './getGridBandwidthCtrlRule.js';
import { registerGetGridBlockListTool } from './getGridBlockList.js';
import { registerGetGridClientHistoryTool } from './getGridClientHistory.js';
import { registerGetGridDashboardIpsecTunnelStatsTool } from './getGridDashboardIpsecTunnelStats.js';
import { registerGetGridDashboardOpenVpnTunnelStatsTool } from './getGridDashboardOpenVpnTunnelStats.js';
import { registerGetGridDashboardTunnelStatsTool } from './getGridDashboardTunnelStats.js';
import { registerGetGridDenyMacFilteringTool } from './getGridDenyMacFiltering.js';
import { registerGetGridEapRuleTool } from './getGridEapRule.js';
import { registerGetGridGatewayRuleTool } from './getGridGatewayRule.js';
import { registerGetGridIpMacBindingTool } from './getGridIpMacBinding.js';
import { registerGetGridKnownClientsTool } from './getGridKnownClients.js';
import { registerGetGridOtoNatsTool } from './getGridOtoNats.js';
import { registerGetGridPolicyRoutingTool } from './getGridPolicyRouting.js';
import { registerGetGridSessionLimitRuleTool } from './getGridSessionLimitRule.js';
import { registerGetGridSignatureTool } from './getGridSignature.js';
import { registerGetGridVirtualWanTool } from './getGridVirtualWan.js';
import { registerGetIgmpTool } from './getIgmp.js';
import { registerGetInterfaceLanNetworkTool } from './getInterfaceLanNetwork.js';
import { registerGetInterfaceLanNetworkV2Tool } from './getInterfaceLanNetworkV2.js';
import { registerGetInterferenceTool } from './getInterference.js';
import { registerGetInternetTool } from './getInternet.js';
import { registerGetInternetBasicPortInfoTool } from './getInternetBasicPortInfo.js';
import { registerGetInternetInfoTool } from './getInternetInfo.js';
import { registerGetInternetLoadBalanceTool } from './getInternetLoadBalance.js';
import { registerGetIpMacBindingGeneralSettingTool } from './getIpMacBindingGeneralSetting.js';
import { registerGetIpsConfigTool } from './getIpsConfig.js';
import { registerGetIpsecVpnStatsTool } from './getIpsecVpnStats.js';
import { registerGetIspLoadTool } from './getIspLoad.js';
import { registerGetLanNetworkListTool } from './getLanNetworkList.js';
import { registerGetLanNetworkListV2Tool } from './getLanNetworkListV2.js';
import { registerGetLanProfileListTool } from './getLanProfileList.js';
import { registerGetLldpSettingTool } from './getLldpSetting.js';
import { registerGetMacAuthSettingTool } from './getMacAuthSetting.js';
import { registerGetMacAuthSsidsTool } from './getMacAuthSsids.js';
import { registerGetMacFilteringGeneralSettingTool } from './getMacFilteringGeneralSetting.js';
import { registerGetMeshSettingTool } from './getMeshSetting.js';
import { registerGetMeshStatisticsTool } from './getMeshStatistics.js';
import { registerGetOsgCustomAclListTool } from './getOsgCustomAclList.js';
import { registerGetOswAclListTool } from './getOswAclList.js';
import { registerGetOswStackLagListTool } from './getOswStackLagList.js';
import { registerGetOuiProfileListTool } from './getOuiProfileList.js';
import { registerGetPastClientNumTool } from './getPastClientNum.js';
import { registerGetPortForwardingStatusTool } from './getPortForwardingStatus.js';
import { registerGetRadioFrequencyPlanningConfigTool } from './getRadioFrequencyPlanningConfig.js';
import { registerGetRadioFrequencyPlanningResultTool } from './getRadioFrequencyPlanningResult.js';
import { registerGetRadiosConfigTool } from './getRadiosConfig.js';
import { registerGetRateLimitProfilesTool } from './getRateLimitProfiles.js';
import { registerGetRemoteLoggingSettingTool } from './getRemoteLoggingSetting.js';
import { registerGetRetryAndDroppedRateTool } from './getRetryAndDroppedRate.js';
import { registerGetRFScanResultTool } from './getRFScanResult.js';
import { registerGetRoamingSettingTool } from './getRoamingSetting.js';
import { registerGetRogueApsTool } from './getRogueAps.js';
import { registerGetRoutingTableTool } from './getRoutingTable.js';
import { registerGetSessionLimitTool } from './getSessionLimit.js';
import { registerGetSnmpSettingTool } from './getSnmpSetting.js';
import { registerGetSpeedTestResultsTool } from './getSpeedTestResults.js';
import { registerGetSshSettingTool } from './getSshSetting.js';
import { registerGetSsidDetailTool } from './getSsidDetail.js';
import { registerGetSsidListTool } from './getSsidList.js';
import { registerGetSsidsBySiteTool } from './getSsidsBySite.js';
import { registerGetStackNetworkListTool } from './getStackNetworkList.js';
import { registerGetStackPortsTool } from './getStackPorts.js';
import { registerGetStaticRoutingInterfaceListTool } from './getStaticRoutingInterfaceList.js';
import { registerGetSwitchDetailTool } from './getSwitchDetail.js';
import { registerGetSwitchDot1xSettingTool } from './getSwitchDot1xSetting.js';
import { registerGetSwitchGeneralConfigTool } from './getSwitchGeneralConfig.js';
import { registerGetSwitchStackDetailTool } from './getSwitchStackDetail.js';
import { registerGetThreatCountTool } from './getThreatCount.js';
import { registerGetThreatDetailTool } from './getThreatDetail.js';
import { registerGetThreatListTool } from './getThreatList.js';
import { registerGetTopThreatsTool } from './getTopThreats.js';
import { registerGetTrafficDistributionTool } from './getTrafficDistribution.js';
import { registerGetUplinkWiredDetailTool } from './getUplinkWiredDetail.js';
import { registerGetUpnpSettingTool } from './getUpnpSetting.js';
import { registerGetUrlFilterGeneralTool } from './getUrlFilterGeneral.js';
import { registerGetVpnSettingsTool } from './getVpnSettings.js';
import { registerGetVpnTunnelStatsTool } from './getVpnTunnelStats.js';
import { registerGetWanLanStatusTool } from './getWanLanStatus.js';
import { registerGetWanPortsConfigTool } from './getWanPortsConfig.js';
import { registerGetWidsTool } from './getWids.js';
import { registerGetWidsBlacklistTool } from './getWidsBlacklist.js';
import { registerGetWlanGroupListTool } from './getWlanGroupList.js';
import { registerListAllSsidsTool } from './listAllSsids.js';
import { registerListClientsTool } from './listClients.js';
import { registerListClientsActivityTool } from './listClientsActivity.js';
import { registerListClientsPastConnectionsTool } from './listClientsPastConnections.js';
import { registerListDevicesTool } from './listDevices.js';
import { registerListDevicesStatsTool } from './listDevicesStats.js';
import { registerListEapAclsTool } from './listEapAcls.js';
import { registerListGlobalAlertsTool } from './listGlobalAlerts.js';
import { registerListGlobalEventsTool } from './listGlobalEvents.js';
import { registerListGroupProfilesTool } from './listGroupProfiles.js';
import { registerListMostActiveClientsTool } from './listMostActiveClients.js';
import { registerListOsgAclsTool } from './listOsgAcls.js';
import { registerListPendingDevicesTool } from './listPendingDevices.js';
import { registerListPolicyRoutesTool } from './listPolicyRoutes.js';
import { registerListPortForwardingRulesTool } from './listPortForwardingRules.js';
import { registerListRadiusProfilesTool } from './listRadiusProfiles.js';
import { registerListSiteAlertsTool } from './listSiteAlerts.js';
import { registerListSiteAuditLogsTool } from './listSiteAuditLogs.js';
import { registerListSiteEventsTool } from './listSiteEvents.js';
import { registerListSitesTool } from './listSites.js';
import { registerListSiteThreatManagementTool } from './listSiteThreatManagement.js';
import { registerListSiteToSiteVpnsTool } from './listSiteToSiteVpns.js';
import { registerListStaticRoutesTool } from './listStaticRoutes.js';
import { registerListSwitchNetworksTool } from './listSwitchNetworks.js';
import { registerListTimeRangeProfilesTool } from './listTimeRangeProfiles.js';
import { registerSearchDevicesTool } from './searchDevices.js';
import { registerSetClientRateLimitTool } from './setClientRateLimit.js';
import { registerSetClientRateLimitProfileTool } from './setClientRateLimitProfile.js';

export function registerAllTools(server: McpServer, client: OmadaClient): void {
    // Site operations
    registerListSitesTool(server, client);

    // Device operations
    registerListDevicesTool(server, client);
    registerGetDeviceTool(server, client);
    registerGetSwitchStackDetailTool(server, client);
    registerGetSwitchDetailTool(server, client);
    registerGetGatewayDetailTool(server, client);
    registerGetGatewayWanStatusTool(server, client);
    registerGetGatewayLanStatusTool(server, client);
    registerGetGatewayPortsTool(server, client);
    registerGetApDetailTool(server, client);
    registerGetApRadiosTool(server, client);
    registerGetStackPortsTool(server, client);
    registerListPendingDevicesTool(server, client);
    registerSearchDevicesTool(server, client);
    registerListDevicesStatsTool(server, client);
    // Issue #36 — Device management read tools
    registerGetAllDeviceBySiteTool(server, client);
    registerGetFirmwareInfoTool(server, client);
    registerGetGridAutoCheckUpgradeTool(server, client);
    registerListSwitchNetworksTool(server, client);
    registerGetSwitchGeneralConfigTool(server, client);
    registerGetCableTestLogsTool(server, client);
    registerGetCableTestFullResultsTool(server, client);
    registerGetOswStackLagListTool(server, client);
    registerGetStackNetworkListTool(server, client);
    registerGetApUplinkConfigTool(server, client);
    registerGetRadiosConfigTool(server, client);
    registerGetApVlanConfigTool(server, client);
    registerGetMeshStatisticsTool(server, client);
    registerGetRFScanResultTool(server, client);
    registerGetSpeedTestResultsTool(server, client);
    registerGetApSnmpConfigTool(server, client);
    registerGetApLldpConfigTool(server, client);
    registerGetApGeneralConfigTool(server, client);
    registerGetUplinkWiredDetailTool(server, client);
    registerGetDownlinkWiredDevicesTool(server, client);

    // Client operations
    registerListClientsTool(server, client);
    registerGetClientTool(server, client);
    registerListMostActiveClientsTool(server, client);
    registerListClientsActivityTool(server, client);
    registerListClientsPastConnectionsTool(server, client);
    registerGetClientDetailTool(server, client);
    registerGetGridKnownClientsTool(server, client);
    registerGetGridClientHistoryTool(server, client);
    registerGetClientsDistributionTool(server, client);
    registerGetPastClientNumTool(server, client);

    // Rate limit operations
    registerGetRateLimitProfilesTool(server, client);
    registerSetClientRateLimitTool(server, client);
    registerSetClientRateLimitProfileTool(server, client);
    registerDisableClientRateLimitTool(server, client);

    // Security / threat operations
    registerGetThreatListTool(server, client);
    registerGetTopThreatsTool(server, client);
    registerListSiteThreatManagementTool(server, client);

    // Network operations
    registerGetInternetInfoTool(server, client);
    registerGetWanLanStatusTool(server, client);
    registerGetPortForwardingStatusTool(server, client);
    registerListPortForwardingRulesTool(server, client);
    registerGetLanNetworkListTool(server, client);
    registerGetLanProfileListTool(server, client);
    registerGetWlanGroupListTool(server, client);
    registerGetSsidListTool(server, client);
    registerGetSsidDetailTool(server, client);
    registerListAllSsidsTool(server, client);
    registerGetSsidsBySiteTool(server, client);
    registerGetRadioFrequencyPlanningConfigTool(server, client);
    registerGetRadioFrequencyPlanningResultTool(server, client);
    registerGetBandSteeringSettingTool(server, client);
    registerGetBeaconControlSettingTool(server, client);
    registerGetChannelLimitSettingTool(server, client);
    registerGetMeshSettingTool(server, client);
    registerGetRoamingSettingTool(server, client);
    registerGetOuiProfileListTool(server, client);
    registerGetMacAuthSettingTool(server, client);
    registerGetMacAuthSsidsTool(server, client);
    registerGetMacFilteringGeneralSettingTool(server, client);
    registerGetGridAllowMacFilteringTool(server, client);
    registerGetGridDenyMacFilteringTool(server, client);
    registerGetSwitchDot1xSettingTool(server, client);
    registerGetEapDot1xSettingTool(server, client);

    // Firewall / ACL / IPS / URL-filter tools (issue #37)
    registerGetAclConfigTypeSettingTool(server, client);
    registerGetOsgCustomAclListTool(server, client);
    registerGetOswAclListTool(server, client);
    registerGetIpsConfigTool(server, client);
    registerGetGridSignatureTool(server, client);
    registerGetGridAllowListTool(server, client);
    registerGetGridBlockListTool(server, client);
    registerGetAttackDefenseSettingTool(server, client);
    registerGetUrlFilterGeneralTool(server, client);
    registerGetGridGatewayRuleTool(server, client);
    registerGetGridEapRuleTool(server, client);
    registerGetFirewallSettingTool(server, client);
    registerGetVpnSettingsTool(server, client);
    registerListSiteToSiteVpnsTool(server, client);
    registerListOsgAclsTool(server, client);
    registerListEapAclsTool(server, client);
    registerListStaticRoutesTool(server, client);
    registerGetStaticRoutingInterfaceListTool(server, client);
    registerListPolicyRoutesTool(server, client);
    registerGetGridPolicyRoutingTool(server, client);
    registerGetGridOtoNatsTool(server, client);
    registerGetAlgTool(server, client);
    registerGetUpnpSettingTool(server, client);
    registerGetDdnsGridTool(server, client);
    registerGetDhcpReservationGridTool(server, client);
    registerGetGridIpMacBindingTool(server, client);
    registerGetIpMacBindingGeneralSettingTool(server, client);
    registerGetLanNetworkListV2Tool(server, client);
    registerGetInterfaceLanNetworkTool(server, client);
    registerGetInterfaceLanNetworkV2Tool(server, client);
    registerGetBandwidthControlTool(server, client);
    registerGetGridBandwidthCtrlRuleTool(server, client);
    registerGetSessionLimitTool(server, client);
    registerGetGridSessionLimitRuleTool(server, client);
    registerGetSnmpSettingTool(server, client);
    registerGetLldpSettingTool(server, client);
    registerGetRemoteLoggingSettingTool(server, client);
    registerGetAccessControlTool(server, client);
    registerGetDnsCacheSettingTool(server, client);
    registerGetDnsProxyTool(server, client);
    registerGetIgmpTool(server, client);
    registerGetInternetLoadBalanceTool(server, client);
    registerGetWanPortsConfigTool(server, client);
    registerGetInternetBasicPortInfoTool(server, client);
    registerGetInternetTool(server, client);
    registerGetGridVirtualWanTool(server, client);
    registerListRadiusProfilesTool(server, client);
    registerListGroupProfilesTool(server, client);
    registerGetApplicationControlStatusTool(server, client);
    registerGetSshSettingTool(server, client);
    registerListTimeRangeProfilesTool(server, client);

    // Monitor / dashboard operations
    registerGetDashboardWifiSummaryTool(server, client);
    registerGetDashboardSwitchSummaryTool(server, client);
    registerGetDashboardTrafficActivitiesTool(server, client);
    registerGetDashboardPoEUsageTool(server, client);
    registerGetDashboardTopCpuUsageTool(server, client);
    registerGetDashboardTopMemoryUsageTool(server, client);
    registerGetDashboardMostActiveSwitchesTool(server, client);
    registerGetDashboardMostActiveEapsTool(server, client);
    registerGetDashboardOverviewTool(server, client);
    registerGetTrafficDistributionTool(server, client);
    registerGetRetryAndDroppedRateTool(server, client);
    registerGetIspLoadTool(server, client);
    registerGetChannelsTool(server, client);
    registerGetInterferenceTool(server, client);
    registerGetGridDashboardTunnelStatsTool(server, client);
    registerGetGridDashboardIpsecTunnelStatsTool(server, client);
    registerGetGridDashboardOpenVpnTunnelStatsTool(server, client);

    // Insight operations
    registerGetWidsTool(server, client);
    registerGetWidsBlacklistTool(server, client);
    registerGetRogueApsTool(server, client);
    registerGetVpnTunnelStatsTool(server, client);
    registerGetIpsecVpnStatsTool(server, client);
    registerGetRoutingTableTool(server, client);
    registerGetThreatDetailTool(server, client);
    registerGetThreatCountTool(server, client);

    // Log operations
    registerListSiteEventsTool(server, client);
    registerListSiteAlertsTool(server, client);
    registerListSiteAuditLogsTool(server, client);
    registerListGlobalEventsTool(server, client);
    registerListGlobalAlertsTool(server, client);
}
